### ISSUE TITLE
Implement workflow for building OCI images and pushing them to Github Packages

### ISSUE THREAD

**Issue by enpaul** [freedomofpress/actionslib#17]
We need a generic workflow that can support building an OCI image from a Containerfile, applying tags, and pushing to a registry. For now, the workflow only needs to support pushing to a [Github Packages Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry), though some care should be taken to allow for extension to support other registries in the future if we want it. The workflow should also support building without publishing for testing purposes. 

Ideally, I'd like a single workflow call to support building+publishing multiple containers in a given repository (to speed up the process) but I don't think that's necessarily practical. I suspect the limitation we'll run into there is that parameters passed into called workflows are all forced into strings which will limit the data structure we can provide. Regardless, the efficiency losses from needing to call this workflow once per target container should be minimal.

**Input specification:**

```yaml
---
context:  # Path to the root of the image build context
  type: path
  default: "."
  example: src/some/sub/path/

containerfile:  # Name of the containerfile in the build context directory to build
  type: string
  default: Containerfile
  example: Dockerfile.prod

build-args:  # Map of extra build args to be passed to the build command as ``--build-arg="<key>=<value>"```
  type: map
  default: {}
  example:
    a-custom-parameter: someValue
    something-else: FoobarAnd_also_Baz.json

registry:  # Registry URL to push to. If not provided, image will not be pushed
  type: Optional(string)
  default: null
  example: ghcr.io/freedomofpress/my-container

tags:  # List of tags to apply to the image when pushed
  type: List(string)
  default: [<commit sha>]
  example:
  - latest
  - v1.2.3

create-artifact:  # Whether to create an Actions artifact of the container image. Only needed if the image is used elsewhere in the calling workflow
  type: bool
  default: false

registry-auth-token:  # Github token to use for authenticating to the registry
  type: string
  default: null
```

**Output specification:**

```yaml
---
image-digest: 
  desc: SHA checksum digest of the built image
  example: sha256:5903c95511b4c6b570cc9c6845251131b83df0376ba023494e537c685d1e7308

registry-url: 
  desc: Canonical URL of the uploaded image on the registry. Is ``null`` if no ``registry`` input was provided
  example: ghcr.io/freedomofpress/some-container@sha256:a8e040c6324ea5e7ec1be5f8e6fa5244fc2ce5feedbb3309116e10a6c5a4f88a

artifact-name:
  desc: Name of the artifact containing the image archive. Is ``null` if the ``create-artifact`` input is ``false``
  example: image-some-container-1122334455
```
